name: cd

on:
  release:
    types: [ created ]

jobs:
  ci:
    runs_on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/ci
        with:
          username: ${{ inputs.username }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM registry
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}      
  