name: cd

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  publish:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Use Node.js LTS (Gallium)
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to NPM registry
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}      
  